### ISSUE TITLE
cannot download dependencies

### ISSUE THREAD

**Issue by nickhuan** [uos/pluto_robot#2]
Thank you for making the great packages, especially the move base flex.

I actually found out mesh_navigation when I was checking out move_base_flex. The readme in mesh_navigation direct me here. 

I tried download this repo and use catkin_make to compile. 
"resource not found: uos_common_urdf" after "running roslaunch pluto_gazebo pluto_gazebo.launch"

Then follow readme but cannot download rosinstall file:
ERROR in config: Unable to download URL [https://raw.githubusercontent.com/uos/uos_rosinstalls/master/pluto.rosinstall]: HTTP Error 404: Not Found

best regards,
Zhonghuan

**Comment by mklpiening** [comment]
The rosinstall has been added so you should now be able to set this workspace up. For now you however need to compile the lvr2 library from source. For more information check the [lvr2 repository](https://github.com/uos/lvr2).

**Comment by nickhuan** [comment]
> The rosinstall has been added so you should now be able to set this workspace up. For now you however need to compile the lvr2 library from source. For more information check the [lvr2 repository](https://github.com/uos/lvr2).

Hi @mklpiening, I installed lvr2: cmake, make and make install into /usr/local, but when I catkin_make to compile the 4 ros meta-packages I still received following errors like:

```
dir_of_catkin/pluto_ws/src/mesh_navigation/mesh_map/src/mesh_map.cpp:55:
/opt/ros/melodic/include/lvr2/io/hdf5/ChannelIO.hpp:23:9: error: ‘HighFive’ has not been declared
         HighFive::Group& g,
         ^~~~~~~~
```
It seems like it will find header file in /opt/ros/melodic/include/lvr2 instead of /usr/local/include/lvr2/

**Comment by mklpiening** [comment]
Hi, i was able to reproduce your error when having both the pre-compiled lvr2 version from the ros repo as well as the self-compiled lvr2 version installed. Removing the package from the ros repo and reinstalling the self compiled version fixed it for me.

You might also need to use the mpi g++ wrapper to fix linker errors when building on some systems:
```
catkin_make -DCMAKE_CXX_COMPILER=/usr/bin/mpicxx
```
